# $File: .travis.yml,v 1.7 2016/04/26 16:24:43 glen Exp $

language: c

# os:
#  - linux
#  - osx

# compiler:
#  - gcc
#  - clang

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc
  - os: osx
    compiler: clang
  - os: linux
    env: TOOLKIT=true

before_install: |
  if [[ ! $TOOLKIT ]] && [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
    sudo apt-get update -qq
    sudo apt-get install -qq automake libtool make python zlib1g-dev
  fi

script: |
  if [[ ! $TOOLKIT ]]; then
    autoreconf -f -i
    ./configure --disable-silent-rules
    make -j4
    make -C tests check
  else
    bash <(curl -s https://runtimeverification.com/toolkit/docker/bash) nightly-2018-08-31
  fi

notifications:
 email:
  recipients:
   - file-tests@mx.gw.com
  on_success: change
  on_failure: always
